app/models/subject.py
# app/models/subject.py

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column, Integer, String, ForeignKey, UniqueConstraint, Text

from .database import db

class Subject(db.Model):
    __tablename__ = 'subjects'
    SubjectID = Column(Integer, primary_key=True, autoincrement=True)
    Code = Column(String(10), nullable=False)
    SubjectName = Column(String(255), nullable=False)
    UniqueConstraint('Code', name='uq_subjects_code')

app/views/archive.py
from flask import Blueprint, render_template, url_for,send_file , redirect ,current_app ,request
from models.course import Course
from models.semester import Semester
from models.subject import Subject
from models.question_paper import QuestionPaper
from models.subject_semester import SubjectSemester
from models.question import Question
import base64
from urllib.parse import unquote
import io
import base64
from PIL import Image, ImageDraw
from models.cache import cache

archive_bp = Blueprint('archive', __name__, template_folder='templates')

@archive_bp.route('/')
@cache.memoize(timeout=120) 
def index():
    courses = Course.query.all()
    return render_template('archive.html', courses=courses)

@archive_bp.route('/courses/<int:course_id>')
@cache.memoize(timeout=120) 
def get_semesters(course_id):
    course = Course.query.get(course_id)
    semesters = Semester.query.filter_by(CourseID=course_id).all()
    return render_template('semesters.html', course=course, semesters=semesters)

@archive_bp.route('/courses/<int:course_id>/semesters/<int:semester_id>')
@cache.memoize(timeout=120) 
def get_subjects(course_id, semester_id):
    course = Course.query.get(course_id)
    semester = Semester.query.get(semester_id)
    # Assuming SubjectSemester has a relationship with Subject
    subjects = Subject.query.join(SubjectSemester).filter(SubjectSemester.SemesterID == semester_id).all()
    return render_template('subjects.html', course=course, semester=semester, subjects=subjects)




@archive_bp.route('/courses/<int:course_id>/semesters/<int:semester_id>/subjects/<int:subject_id>/papers')
@cache.memoize(timeout=10)
def get_question_papers(course_id, semester_id, subject_id):
    course = Course.query.get(course_id)
    semester = Semester.query.get(semester_id)
    subject = Subject.query.get(subject_id)
    question_papers = QuestionPaper.query.filter_by(SubjectID=subject_id).all()
    return render_template('question_papers.html', course=course, semester=semester, subject=subject, question_papers=question_papers)


def get_question_start_position(question_number):
    # Query the database to get the question based on the question number
    question = Question.query.filter_by(QuestionNumber=question_number).first()
    if question:
        # Parse the coordinates to get the start position
        coordinates = question.Coordinates.split('-')
        if len(coordinates) == 2:
            start_position = int(coordinates[0])
            return start_position
    return None

# In your backend route handler


@archive_bp.route('/courses/<int:course_id>/semesters/<int:semester_id>/subjects/<int:subject_id>/papers/<int:paper_id>')
@cache.memoize(timeout=60)  # Cache the result for 60 seconds
def get_paper_details(course_id, semester_id, subject_id, paper_id):

    if cache.get(request.path):
        # Log cache hit
        current_app.logger.info("Cache hit")
        return cache.get(request.path)

    # Log cache miss
    current_app.logger.info("Cache miss")


     # Fetch paper details (including the file path)
    paper = QuestionPaper.query.get(paper_id)
    
    # Read the image file
    with Image.open(paper.FilePath) as img:
        # Define the number of strips and their height
        num_strips = 8  # Increase the number of strips for thinner strips
        strip_height = img.height // num_strips
        
        # Initialize an empty list to store strip data
        strip_data = []
        
        # Iterate over the image and extract each strip
        for i in range(num_strips):
            # Define the bounding box for the current strip
            box = (0, i * strip_height, img.width, (i + 1) * strip_height)
            
            # Crop the strip from the image
            strip_img = img.crop(box)
            
            # Convert the strip to base64 string
            buffered = io.BytesIO()
            strip_img.save(buffered, format='JPEG')
            buffered.seek(0)
            strip_base64 = base64.b64encode(buffered.getvalue()).decode('utf-8')
            
            # Append the strip data to the list
            strip_data.append(strip_base64)
        
        # Ensure that the strip data list maintains the correct order
        strip_data = sorted(strip_data, key=lambda x: strip_data.index(x))
        
        # Calculate the aspect ratio of the original image
        aspect_ratio = img.width / img.height
        start_position=1
        # Check if question number is present in the URL
        question_number = request.args.get('question_number')
        
        if (question_number and int(question_number) in range(1,6)):
            # Get the start position of the question
            start_position = get_question_start_position(question_number)
            if start_position:
                # Calculate the scroll height based on the start position and aspect ratio
                scroll_height = (start_position / aspect_ratio) * strip_height
            else:
                scroll_height = 0
        else:
            scroll_height = 0
        
        # Render the template with the strip data and scroll height
        return render_template('paper_details.html', strip_data=strip_data, scroll_height=scroll_height, scrollV=img.height/start_position , aspect_ratio = aspect_ratio)


@archive_bp.route('/papers/<string:paper_code>/<string:exam_type>/<int:exam_year>/<int:question_number>')
@cache.memoize(timeout=60)  # Cache the result for 60 seconds
def redirect_to_paper_by_code(paper_code, exam_type, exam_year, question_number):
    # Decode the paper code
    decoded_paper_code = unquote(paper_code)
    # Query the Subject table to get the SubjectID based on the provided subject code
    subject = Subject.query.filter_by(Code=decoded_paper_code).first()
    if subject:
        # Query the SubjectSemester table to find the first instance where the SubjectID appears
        subject_semester = SubjectSemester.query.filter_by(SubjectID=subject.SubjectID).first()
        if subject_semester:
            # Retrieve the SemesterID
            semester_id = subject_semester.SemesterID
            
            # Query the Semester table to get the CourseID
            semester = Semester.query.get(semester_id)
            if semester:
                # Query the QuestionPaper table to get the paper ID based on the provided information
                paper = QuestionPaper.query.filter_by(SubjectID=subject.SubjectID,
                                                        ExamType=exam_type,
                                                        Year=exam_year).first()
                if paper:
                    # Construct the URL for the paper details page
                    redirect_url = url_for('archive.get_paper_details',
                                           course_id=semester.CourseID,
                                           semester_id=semester_id,
                                           subject_id=subject.SubjectID,
                                           paper_id=paper.PaperID,
                                           question_number=question_number)
                    
                    # Redirect to the paper details page
                    return redirect(redirect_url)
    
    # Handle case where paper details are not found
    return "Paper details not found", 404

app/views/logininfo.py
# app/logininfo.py

from flask import Blueprint, render_template, session

logininfo_blueprint = Blueprint('logininfo', __name__)

@logininfo_blueprint.route('/logininfo')
def logininfo():
    # Retrieve session information
    user_id = session.get('user_id')
    email = session.get('email')
    # You can add more session data as needed

    # Pass session information to the frontend template
    return render_template('logininfo.html', user_id=user_id, email=email)

app/views/posts.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash, session,jsonify
from models.posts import Post
from models.database import db
from models.sessions import Session
from models.threads import Thread
from models.category import Category
from models.categorypost import CategoryPost
from models.likes import LikeDislike
# from .models import Post, Category, CategoryPost
# from models.category import Category
from views.checksession import check_session
# from markdown2 import markdown
import mistune
posts_bp = Blueprint('posts', __name__)

@posts_bp.route('/<category>')
def index(category=''):
    # Fetch all posts from the database that belong to the specified category
    user, admin_rights = check_session()
    
    per_page = 5
    category_id = Category.query.filter_by(CategoryName=category).first().CategoryID
    
    # Query distinct post IDs associated with the specified category
    post_ids = CategoryPost.query.filter_by(category_id=category_id).with_entities(CategoryPost.post_id).distinct().all()
    post_ids = [post_id for post_id, in post_ids]
    
    # Fetch paginated posts based on the distinct post IDs
    posts = Post.query.filter(Post.PostID.in_(post_ids)).filter_by(Approved=1).paginate(per_page=per_page)
    
    for post in posts.items:
        post.Content = mistune.markdown(post.Content)
        # Fetch the thread associated with the post
        post.thread = Thread.query.filter_by(PostID=post.PostID).first()
        commentTime = post.TimeStamp
        # dt_object = datetime.strptime(post.TimeStamp, '%Y-%m-%d %H:%M:%S')
        post.commentTime = commentTime.strftime('%B,%d %Y')


        post.likes = LikeDislike.query.filter_by(PostID=post.PostID, Action=1).count()
        post.dislikes = LikeDislike.query.filter_by(PostID=post.PostID, Action=-1).count()

        if user:
                # Check if the current user has liked or disliked the comment
                liked = LikeDislike.query.filter_by(UserID=user.id, PostID=post.PostID, Action=1).first()
                disliked = LikeDislike.query.filter_by(UserID=user.id, PostID=post.PostID, Action=-1).first()
                post.has_liked = True if liked else False
                post.has_disliked = True if disliked else False
        else:
                # If the user is not logged in, set both has_liked and has_disliked to False
                post.has_liked = False
                post.has_disliked = False

    return render_template('posts.html', posts=posts, user=user, category=category )


        



@posts_bp.route('/load-more')
def load_more_posts():
    page = request.args.get('page', 1, type=int)  # Get the page number from the request query parameters
    per_page = 5  # Number of posts to load per page
    category_name = request.args.get('category')  # Get the category name from the request query parameters

    # Fetch category ID based on the category name
    category = Category.query.filter_by(CategoryName=category_name).first()
    if category:
        category_id = category.CategoryID

        # Query distinct post IDs associated wip.strftime('%B,%d %Y')

# Format the datetime object into your desired formatth the specified category
        post_ids = CategoryPost.query.filter_by(category_id=category_id).with_entities(CategoryPost.post_id).distinct().all()
        post_ids = [post_id for post_id, in post_ids]

        # Fetch paginated posts based on the distinct post IDs
        posts = Post.query.filter(Post.PostID.in_(post_ids)).filter_by(Approved=1).paginate(page=page, per_page=per_page, error_out=False)

        # Check if there are more posts available
        has_next = posts.has_next
        for post in posts.items:
            post.Content = mistune.markdown(post.Content)
            # Fetch the thread associated with the post
            
            post.thread = Thread.query.filter_by(PostID=post.PostID).first()
            # dt_object = datetime.strptime(, '%Y-%m-%d %H:%M:%S')
            commentTime = post.TimeStamp
            # dt_object = datetime.strptime(post.TimeStamp, '%Y-%m-%d %H:%M:%S')
            post.commentTime = commentTime.strftime('%B,%d %Y')
        # Prepare posts data for JSON response
        posts_data = [{
            'UserID': post.UserID,
            'Content': post.Content,
            'TimeStamp': post.TimeStamp,
            'DifficultyLevel': post.DifficultyLevel,
            'ThreadID': post.thread.ThreadID
        } for post in posts.items]

        return jsonify({'posts': posts_data, 'has_next': has_next})
    else:
        return jsonify({'error': 'Category not found'})





@posts_bp.route('/submit/<category>', methods=['POST'])
def submit_post(category):
    # Retrieve post content from the form
    post_content = request.form.get('post_content')
    
    # Get the current timestamp
    current_time = datetime.utcnow()
    
    # Get the session token from the session
    session_token = session.get('session_token')
    
    # Query the Session table to get the user_id based on the session_token
    session_info = Session.query.filter_by(sid=session_token).first()
    
    if session_info:
        user_id = session_info.user_id
        
        # Create a new post object with the provided data
        new_post = Post(
            UserID=user_id,
            Content=post_content,
            TimeStamp=current_time,
            DifficultyLevel=1
        )
        db.session.add(new_post)

        # Commit the changes to the database to generate the PostID
        db.session.commit()

        # Now you can access the PostID from the new_post object
        post_id = new_post.PostID

        # Create a new CategoryPost object with the provided data
        new_cat_post = CategoryPost(
            category_id=Category.query.filter_by(CategoryName=category).first().CategoryID,
            post_id=post_id
        )

        # Add the new category-post relationship to the database session
        db.session.add(new_cat_post)

        # Commit the changes to the database
        db.session.commit()
        return('Post submitted successfully', 'success')
        
    else:
        flash('Session expired or invalid', 'error')
        
    # Redirect to the homepage
    return jsonify({'posts': 'something something'})







 
@posts_bp.route('/categories', methods=['GET', 'POST'])
def categories():

    user, admin_rights = check_session()
    if request.method == 'POST':
        category_name = request.form['category_name']
        description = request.form['description']  
        if category_name:
            # Check if category name already exists in the database
            existing_category = Category.query.filter_by(CategoryName=category_name).first()
            if existing_category:
                # If category already exists, redirect back to categories page with a message
                return render_template('categories.html', categories=Category.query.all(), error_message="Category already exists.")
            else:
                # If category does not exist, add it to the database
                new_category = Category(CategoryName=category_name, description=description)
                db.session.add(new_category)
                db.session.commit()
                return redirect(url_for('posts.categories'))
    categories = Category.query.all()
    return render_template('categories.html', categories=categories , user=user)




@posts_bp.route('/handle-postlikes/<postId>/<action>', methods=['POST'])
def handle_likes(postId, action):
    user, admin_rights = check_session()

    if request.method == 'POST':
        # Check if the action is either 'like' or 'dislike' or 'removeopinion'
        if action in ['like', 'dislike', 'removeopinion']:
            # Check if the action is valid
            if action == 'like':
                # Check if the user already has an opinion on this post
                existing_opinion = LikeDislike.query.filter_by(UserID=user.id, PostID=postId).first()
                if existing_opinion:
                    existing_opinion.Action = 1  # Update the existing opinion to like
                else:
                    # Create a new entry in the database
                    new_opinion = LikeDislike(UserID=user.id, PostID=postId, Action=1)
                    db.session.add(new_opinion)
                db.session.commit()

            elif action == 'dislike':
                # Check if the user already has an opinion on this post
                existing_opinion = LikeDislike.query.filter_by(UserID=user.id, PostID=postId).first()
                if existing_opinion:
                    existing_opinion.Action = -1  # Update the existing opinion to dislike
                else:
                    # Create a new entry in the database
                    new_opinion = LikeDislike(UserID=user.id, PostID=postId, Action=-1)
                    db.session.add(new_opinion)
                db.session.commit()

            elif action == 'removeopinion':
                # Check if the user already has an opinion on this post
                existing_opinion = LikeDislike.query.filter_by(UserID=user.id, PostID=postId).first()
                if existing_opinion:
                    db.session.delete(existing_opinion)  # Remove the existing opinion from the database
                    db.session.commit()

            # Return success message
            return 'Action successfully performed'

    # Handle invalid actions or other HTTP methods
    return 'Invalid action or method', 400

app/templates/archive.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Archive Home</title>

    <style>
      * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: "Montserrat", sans-serif;
        font-family: "Nunito", sans-serif;
      }

      .container ul {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        grid-gap: 10px;
      }

      .container ul li a {
        display: flex;
        justify-content: center;
        text-align: center;
        align-items: center;
        flex-direction: column;
        padding: 20px;
        text-align: center;
        text-decoration: none;
        list-style: none;
      }

      .container ul li a {
        color: black;
        text-decoration: none;
        list-style: none;
      }

      .main {
        position: absolute;
        top: 40%;
        left: 50%;
        transform: translate(-50%, -50%);
        display: flex;
        align-items: center;
        flex-direction: column;
        width: 80%;
      }

      .main h2 {
        font-size: 50px;
      }

      .search-container {
        margin-bottom: 20px;
      }

      .search-container input[type="text"] {
        padding: 10px;
        width: 200px;
        border: 1px solid #ccc;
        border-radius: 5px;
      }

      /* Style the button */
      .search-container button {
        padding: 10px 15px;
        background-color: #ddb06bd5;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
      }

      /* On hover, change background color */
      .search-container button:hover {
        background-color: #ddb06bd5;
      }

      .nav {
        display: flex;
        height: 100%;
        width: 80%;
        margin-bottom: 50px;
        justify-content: space-between;
      }

      .btn {
        padding: 10px 30px;
        background-color: #ddb06bd5;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 40px;
        margin-left: 40px;
      }
    </style>
  </head>
  <body>
    <div class="main">
      <div class="nav">
        <h2>Courses:</h2>
        <div class="search-container">
          <input type="text" placeholder="Search..." />
          <button type="submit">Search</button>
        </div>
      </div>

      <div class="container">
        <ul>
          {% for course in courses %}
          <li>
            <a
              href="{{ url_for('archive.get_semesters', course_id=course.CourseID) }}"
            >
              <img
                src="{{ url_for('static', filename='folder.svg') }}"
                alt="Your SVG Image"
                height="190"
                width="150"
              />
              {{ course.CourseName }}</a
            >
          </li>
          {% endfor %}
        </ul>
        <button id="btn" class="btn">Back</button>
      </div>
    </div>

    <script>
      const backBtn = document.getElementById("btn");

      function redirectToSearch() {
        // Construct the URL for the search
        const searchUrl = `/`;

        // Redirect to the search URL
        console.log("clicked");
        window.location.href = searchUrl;
      }

      backBtn.addEventListener("click", redirectToSearch);
    </script>
  </body>
</html>

app/templates/backups.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Backups</title>
  </head>
  <body>
    <h1>Available Backups</h1>
    <ul>
      {% for backup in backups %}
      <li>
        <a href="#" onclick="restoreBackup('{{ backup }}')">{{ backup }}</a>
      </li>
      {% endfor %}
    </ul>

    <script>
      function restoreBackup(backupName) {
        if (confirm(`Are you sure you want to restore ${backupName}?`)) {
          fetch(`/admin/restore_backup/${backupName}`, {
            method: 'POST',
          })
            .then((response) => response.json())
            .then((data) => {
              alert(data.message);
              // Optionally, you can redirect or perform additional actions here
            })
            .catch((error) => console.error('Error:', error));
        }
      }
    </script>
  </body>
</html>

app/templates/categories.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Categories</title>
    <style>
      .container {
        display: flex;
        flex-direction: column;
        /* justify-content: center; */
        align-items: center;
        text-align: center;
        height: 100vh;
        width: 100%;
      }
      .cat {
        min-width: 100%;
        max-height: 100%;
      }
      .cat ul {
        display: grid;
        grid-template-columns: repeat(
          3,
          1fr
        ); /* Three columns with equal width */
        grid-gap: 20px; /* Gap between grid items */
        list-style-type: none; /* Remove default bullet points */
      }
      .cat ul a {
        /* Background color */
        /* Padding */
        /* Border */

        font-size: 20px;
        text-decoration: none; /* Optional: remove underline */
        color: rgba(31, 30, 30, 0.704);
      }
      /* 
      .cat ul a li {
        margin-top: 10px;
      } */
      /* Additional CSS for styling the form */
      .container form {
        margin-top: 30px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }

      .container form label {
        display: block; /* Ensure labels are on their own line */
        margin-bottom: 10px; /* Add space below each label */
        font-size: 18px; /* Increase font size for labels */
      }

      .container form input[type="text"] {
        width: 70%; /* Make input field fill the container width */
        padding: 10px; /* Add padding to input field */
        margin-bottom: 20px; /* Add space below input field */
        font-size: 16px; /* Set font size for input field */
        border: 1px solid #ccc; /* Add border to input field */
        border-radius: 5px; /* Add border radius to input field */
        box-sizing: border-box; /* Include padding and border in element's total width and height */
      }

      .container form button {
        padding: 10px 18px; /* Add padding to button */
        font-size: 14px; /* Increase font size for button */
        background-color: #28a745; /* Set background color for button */
        color: #fff; /* Set text color for button */
        border: none; /* Remove border from button */
        border-radius: 5px; /* Add border radius to button */
        cursor: pointer; /* Change cursor to pointer on hover */
        transition: background-color 0.3s ease; /* Add transition effect for background color */
      }

      .container form button:hover {
        background-color: #218838; /* Change background color on hover */
      }

      .form-div {
        /* border: 2px solid red; */
        background-color: #f0f0f0;
        margin-top: 50px;
        width: 66%;
        height: 29%;
        border-radius: 10px;
      }

      body {
        font-family: arial;
      }
      .main {
        margin: 2%;
      }

      .card {
        width: 100%;
        display: inline-block;
        box-shadow: 2px 2px 20px black;
        border-radius: 5px;
        margin: 2%;
      }

      .image img {
        width: 100%;
        border-top-right-radius: 5px;
        border-top-left-radius: 5px;
      }

      .title {
        text-align: center;
        padding: 10px;
      }

      h1 {
        font-size: 20px;
      }

      .des {
        padding: 3px;
        text-align: center;

        padding-top: 10px;
        border-bottom-right-radius: 5px;
        border-bottom-left-radius: 5px;
      }
      .des button {
        margin-top: 40px;
        margin-bottom: 10px;
        background-color: white;
        border: 1px solid black;
        border-radius: 5px;
        padding: 10px;
      }
      .des button:hover {
        background-color: black;
        color: white;
        transition: 0.5s;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Categories</h1>
      <div class="cat">
        <ul>
          {% for category in categories %}

          <li>
            <div class="main">
              <!--cards -->

              <!--cards -->

              <div class="card">
                <div class="image"></div>
                <div class="title">
                  <h1>{{ category.CategoryName }}</h1>
                </div>
                <div class="des">
                  <p>{{ category.Description}}</p>
                  <a
                    href="{{ url_for('posts.index', category=category.CategoryName) }}"
                  >
                    <button>Open posts</button></a
                  >
                </div>
              </div>
            </div>
          </li>

          {% endfor %} {% if user.is_admin %}
          <li>
            <div class="card">
              <h2>Add New Category</h2>
              <form action="/posts/categories" method="post">
                <label for="category_name">Category Name:</label>
                <input
                  type="text"
                  id="category_name"
                  name="category_name"
                  required
                />

                <label for="description">Description:</label>
                <textarea
                  id="description"
                  name="description"
                  rows="4"
                  cols="50"
                ></textarea>

                <button type="submit">Add Category</button>
              </form>
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </body>
</html>

app/templates/result_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Submission Status</title>
  </head>
  <body>
    <h1>Submission Status</h1>
    <p>{{ data }}</p>
  </body>
</html>

app/templates/semesters.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Semesters</title>
    <style>
      * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: "Montserrat", sans-serif;
        font-family: "Nunito", sans-serif;
      }

      .main {
        display: flex;
        align-items: center;
        gap: 100px;
        flex-direction: column;
        width: 100%;
      }

      .sem ul li a {
        width: 60%;
        text-decoration: none;
        list-style: none;
        outline: none;
        text-decoration: none;
        color: black;
      }

      .sem ul li {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
        width: 100%;
        text-decoration: none;
        list-style: none;
        outline: none;
      }

      .sem ul {
        width: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        list-style: none;
        text-decoration: none;
        list-style-type: none;
        outline: none;
      }

      .sem {
        /* border: 2px solid red; */
        background-color: hsl(0, 14%, 98%);
        border: 1px solid black;
        border-radius: 7px;
        height: 70vh;
        width: 30%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }

      .semdiv {
        margin-top: 10px;
        background-color: #fff;
        border: 1px solid black;

        border-radius: 10px;
        height: 6vh;
        width: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }

      .btn {
        padding: 10px 30px;
        background-color: #ddb06bd5;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        margin-left: 40px;
      }
    </style>
  </head>
  <body>
    <div class="main">
      <h1>{{ course.CourseName }}</h1>
      <div class="sem">
        <ul>
          {% for semester in semesters %}

          <li>
            <a
              href="{{ url_for('archive.get_subjects', course_id=course.CourseID, semester_id=semester.SemesterID) }}"
              ><div class="semdiv">{{ semester.SemesterName }}</div></a
            >
          </li>
          {% endfor %}
        </ul>
      </div>
      <button id="btn" class="btn">Back</button>
    </div>

    <script>
      const backBtn = document.getElementById("btn");

      function redirectToSearch() {
        // Construct the URL for the search
        const searchUrl = `/archive/`;

        // Redirect to the search URL
        console.log("clicked");
        window.location.href = searchUrl;
      }

      backBtn.addEventListener("click", redirectToSearch);
    </script>
  </body>
</html>